AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "spec/**/*"
    - "vendor/**/*"
    - "vendor/bundle/**/*"

####################################
## Customization for this project ##
####################################

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/AbcSize:
  Max: 28

Metrics/MethodLength:
  Max: 15

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent
